--
-- ER/Studio Data Architect SQL Code Generation
-- Project :      NYPD_DIMENSION_MODEL.DM1
--
-- Date Created : Thursday, February 13, 2025 16:16:03
-- Target DBMS : Snowflake
--

-- 
-- TABLE: AGE_GROUP_DIM 
--

CREATE TABLE AGE_GROUP_DIM(
    AGE_GROUP_SK       NUMBER(10, 0)    NOT NULL,
    AGE_GROUP_NAME     VARCHAR(50),
    AGE_RANGE_START    NUMBER(3, 0),
    AGE_RANGE_END      NUMBER(3, 0),
    CONSTRAINT PK_AGE_GROUP_SK PRIMARY KEY (AGE_GROUP_SK) 
)
;



-- 
-- TABLE: ARREST_FCT 
--

CREATE TABLE ARREST_FCT(
    ARREST_SK          NUMBER(10, 0)    NOT NULL,
    ARREST_DATE        NUMBER(10, 0)    NOT NULL,
    CRIME_SK           NUMBER(15, 0)    NOT NULL,
    ARRESTEE_SK        CHAR(10)         NOT NULL,
    AGE_GROUP_SK       NUMBER(10, 0)    NOT NULL,
    ARREST_LOCATION    VARCHAR(255)     NOT NULL,
    ARREST_COUNT       NUMBER(1, 0)     DEFAULT 1,
    CONSTRAINT PK_ARREST_SK PRIMARY KEY (ARREST_SK, ARREST_DATE, CRIME_SK, ARRESTEE_SK, AGE_GROUP_SK, ARREST_LOCATION) 
)
;



-- 
-- TABLE: ARRESTEE_DIM 
--

CREATE TABLE ARRESTEE_DIM(
    ARRESTEE_SK     CHAR(10)         NOT NULL,
    AGE_GROUP_SK    NUMBER(10, 0)    NOT NULL,
    ARRESTEE_AGE    NUMBER(3, 0),
    PERP_SEX        CHAR(10),
    PERP_RACE       VARCHAR(20),
    CONSTRAINT PK_ARRESTEE_SK PRIMARY KEY (ARRESTEE_SK, AGE_GROUP_SK) 
)
;



-- 
-- TABLE: CRIME_DIM 
--

CREATE TABLE CRIME_DIM(
    CRIME_SK               NUMBER(15, 0)    NOT NULL,
    OFFENSE_CODE           NUMBER(3, 0),
    OFFENSE_DESCRIPTION    VARCHAR(255),
    PD_CODE                NUMBER(3, 0),
    PD_DESCRIPTION         VARCHAR(255),
    LAW_CODE               VARCHAR(255),
    LAW_CAT_CD             CHAR(10),
    CONSTRAINT PK_CRIME_SK PRIMARY KEY (CRIME_SK) 
)
;



-- 
-- TABLE: DATE_DIM 
--

CREATE TABLE DATE_DIM(
    DATE_SK        NUMBER(10, 0)    NOT NULL,
    FULL_DATE      DATE,
    DAY_NAME       VARCHAR(10),
    DAY_NUM        NUMBER(2, 0),
    MONTH_NAME     VARCHAR(20),
    MONTH_NUM      NUMBER(2, 0),
    QUARTER_NUM    NUMBER(2, 0),
    YEAR_NUM       NUMBER(4, 0),
    IS_WEEKEND     BOOLEAN,
    CONSTRAINT PK_DATE_SK PRIMARY KEY (DATE_SK) 
)
;



-- 
-- TABLE: LOCATION_DIM 
--

CREATE TABLE LOCATION_DIM(
    LOCATION_SK        VARCHAR(255)     NOT NULL,
    ARREST_PRECINCT    NUMBER(10, 0),
    BOROUGH_CODE       CHAR(1),
    LATITUDE           DECIMAL(8, 6),
    LONGITUDE          DECIMAL(9, 6),
    CONSTRAINT PK_LOCATION_SK PRIMARY KEY (LOCATION_SK) 
)
;



-- 
-- TABLE: ARREST_FCT 
--

ALTER TABLE ARREST_FCT ADD CONSTRAINT RefDATE_DIM2 
    FOREIGN KEY (ARREST_DATE)
    REFERENCES DATE_DIM(DATE_SK)
;

ALTER TABLE ARREST_FCT ADD CONSTRAINT RefCRIME_DIM3 
    FOREIGN KEY (CRIME_SK)
    REFERENCES CRIME_DIM(CRIME_SK)
;

ALTER TABLE ARREST_FCT ADD CONSTRAINT RefARRESTEE_DIM5 
    FOREIGN KEY (ARRESTEE_SK, AGE_GROUP_SK)
    REFERENCES ARRESTEE_DIM(ARRESTEE_SK, AGE_GROUP_SK)
;

ALTER TABLE ARREST_FCT ADD CONSTRAINT RefLOCATION_DIM9 
    FOREIGN KEY (ARREST_LOCATION)
    REFERENCES LOCATION_DIM(LOCATION_SK)
;


-- 
-- TABLE: ARRESTEE_DIM 
--

ALTER TABLE ARRESTEE_DIM ADD CONSTRAINT RefAGE_GROUP_DIM1 
    FOREIGN KEY (AGE_GROUP_SK)
    REFERENCES AGE_GROUP_DIM(AGE_GROUP_SK)
;


